# Generated by Django 5.0.6 on 2024-07-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='importancia',
            field=models.TextField(default='Normal', max_length=200, verbose_name='importancia'),
            preserve_default=False,
        ),
    ]
